options: &options
  parameterize_keys: true
  persist_in_safe_mode: true
  identity_map_enabled: true

development:
  <<: *options
  host: localhost
  database: busify_development
  logger: false

test:
  <<: *options
  host: localhost
  database: busify_test

# set these environment variables on your prod server
production:
  <<: *options
  host: <%= ENV['MONGOID_HOST'] %>
  port: <%= ENV['MONGOID_PORT'] %>
  username: <%= ENV['MONGOID_USERNAME'] %>
  password: <%= ENV['MONGOID_PASSWORD'] %>
  database: <%= ENV['MONGOID_DATABASE'] %>
  # slaves:
  #   - host: slave1.local
  #     port: 27018
  #   - host: slave2.local
  #     port: 27019
